# Generated by Django 4.2.4 on 2023-09-01 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0001_initial"),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreviewstoread",
            name="Reviews",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.reviews"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favourite_rankings",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.userfavouriterankings",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pending_premieres",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.userpendingpremieres",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reviews_to_read",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.userreviewstoread",
            ),
        ),
        migrations.AddField(
            model_name="userpendingpremieres",
            name="Premieres",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.pendingpremieres"
            ),
        ),
        migrations.AddField(
            model_name="userfavouriterankings",
            name="Rankings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.rankings"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
