# Generated by Django 4.2.4 on 2023-10-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile",
        ),
    ]
