# Generated by Django 4.2.4 on 2023-10-24 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_customuser_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.userprofile",
            ),
        ),
    ]
