# Generated by Django 4.2.4 on 2023-11-10 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsroomcomments",
            old_name="description",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="premierescomments",
            old_name="description",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="rankingscomments",
            old_name="description",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="reviewscomments",
            old_name="description",
            new_name="comment",
        ),
        migrations.RemoveField(
            model_name="reviewsminiaturesimages",
            name="review",
        ),
        migrations.AddField(
            model_name="newsroom",
            name="content",
            field=models.CharField(default="1", max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newsroomcomments",
            name="date_of_publishing",
            field=models.DateField(default="2023-10-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="premierescomments",
            name="date_of_publishing",
            field=models.DateField(default="2023-01-10"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="premieresminiaturesimages",
            name="description",
            field=models.CharField(default="1", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rankings",
            name="description",
            field=models.CharField(default="1", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rankingscomments",
            name="date_of_publishing",
            field=models.DateField(default="2023-10-10"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rankingsminiaturesimages",
            name="description",
            field=models.CharField(default="1", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reviews",
            name="content",
            field=models.CharField(default="1", max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reviews",
            name="game_title",
            field=models.CharField(default="1", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reviews",
            name="review_minature_image",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.reviewsminiaturesimages",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reviewsminiaturesimages",
            name="description",
            field=models.CharField(default="1", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reviewsminiaturesimages",
            name="game_title",
            field=models.CharField(default="1", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="newsroom",
            name="description",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="newsroomimages",
            name="image",
            field=models.ImageField(
                height_field=200,
                upload_to="blog/static/newsroom_images/",
                width_field=200,
            ),
        ),
        migrations.AlterField(
            model_name="newsroomminiaturesimages",
            name="miniature_image",
            field=models.ImageField(
                upload_to="blog/static/newsroom_miniatures_images/"
            ),
        ),
        migrations.AlterField(
            model_name="newsroomvideo",
            name="video",
            field=models.FileField(upload_to="blog/static/newsroom_videos/"),
        ),
        migrations.AlterField(
            model_name="premieresimages",
            name="image",
            field=models.ImageField(upload_to="blog/static/premieres_images/"),
        ),
        migrations.AlterField(
            model_name="premieresminiaturesimages",
            name="miniature_image",
            field=models.ImageField(
                upload_to="blog/static/rankings_miniatures_images/"
            ),
        ),
        migrations.AlterField(
            model_name="premieresvideo",
            name="video",
            field=models.FileField(upload_to="blog/static/premieres_videos/"),
        ),
        migrations.AlterField(
            model_name="rankingsimages",
            name="image",
            field=models.ImageField(
                height_field=200,
                upload_to="blog/static/rankings_images/",
                width_field=200,
            ),
        ),
        migrations.AlterField(
            model_name="rankingsminiaturesimages",
            name="miniature_image",
            field=models.ImageField(
                upload_to="blog/static/rankings_miniatures_images/"
            ),
        ),
        migrations.AlterField(
            model_name="rankingsvideo",
            name="video",
            field=models.FileField(upload_to="blog/static/rankings_videos/"),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="description",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="reviewscomments",
            name="dislikes",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="reviewscomments",
            name="likes",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="reviewsimages",
            name="image",
            field=models.ImageField(upload_to="blog/static/reviews_images/"),
        ),
        migrations.AlterField(
            model_name="reviewsminiaturesimages",
            name="miniature_image",
            field=models.ImageField(upload_to="blog/media/reviews_miniatures_images/"),
        ),
        migrations.AlterField(
            model_name="reviewsvideo",
            name="video",
            field=models.FileField(upload_to="blog/static/reviews_videos/"),
        ),
    ]
