# Generated by Django 4.2.4 on 2023-11-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_description_newsroomcomments_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewsminiaturesimages",
            name="miniature_image",
            field=models.ImageField(upload_to=""),
        ),
    ]
