# Generated by Django 4.2.4 on 2023-11-11 20:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_reviewsminiaturesimages_miniature_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewsminiaturesimages",
            name="miniature_image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="blog/media/reviews_miniatures_images"
                ),
                upload_to="",
            ),
        ),
    ]
