# Generated by Django 4.2.4 on 2023-11-13 17:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_reviewsimages_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewsimages",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="blog/media"
                ),
                upload_to="reviews_images",
            ),
        ),
    ]
