# Generated by Django 4.2.4 on 2023-11-14 07:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_reviewsimages_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsroomimages",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="blog/media"
                ),
                upload_to="newsroom_images",
            ),
        ),
        migrations.AlterField(
            model_name="newsroomminiaturesimages",
            name="miniature_image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="blog/media"
                ),
                upload_to="newsroom_miniatures_images",
            ),
        ),
        migrations.AlterField(
            model_name="newsroomvideo",
            name="video",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="blog/media"
                ),
                upload_to="newsroom_videos",
            ),
        ),
        migrations.AlterField(
            model_name="premieresimages",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="blog/media"
                ),
                upload_to="premieres_images",
            ),
        ),
        migrations.AlterField(
            model_name="premieresminiaturesimages",
            name="miniature_image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="blog/media"
                ),
                upload_to="rankings_miniatures_images",
            ),
        ),
        migrations.AlterField(
            model_name="premieresvideo",
            name="video",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="blog/media"
                ),
                upload_to="premieres_videos",
            ),
        ),
        migrations.AlterField(
            model_name="rankingsimages",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="blog/media"
                ),
                upload_to="rankings_images",
            ),
        ),
        migrations.AlterField(
            model_name="rankingsminiaturesimages",
            name="miniature_image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="blog/media"
                ),
                upload_to="rankings_miniatures_images",
            ),
        ),
        migrations.AlterField(
            model_name="rankingsvideo",
            name="video",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="blog/media"
                ),
                upload_to="rankings_videos",
            ),
        ),
        migrations.AlterField(
            model_name="reviewsminiaturesimages",
            name="miniature_image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="blog/media"
                ),
                upload_to="reviews_miniatures_images",
            ),
        ),
        migrations.AlterField(
            model_name="reviewsvideo",
            name="video",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="blog/media"
                ),
                upload_to="reviews_videos",
            ),
        ),
    ]
