# Generated by Django 4.2.4 on 2024-01-07 20:58

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_remove_reviews_review_image_reviewsimages_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="premieresminiaturesimages",
            name="premiere",
        ),
        migrations.AddField(
            model_name="pendingpremieres",
            name="premiere",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.premieresminiaturesimages",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="premieresminiaturesimages",
            name="game_title",
            field=models.CharField(default="something", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="premieresminiaturesimages",
            name="miniature_image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="blog/media"
                ),
                upload_to="premieres_miniatures_images",
            ),
        ),
    ]
