# Generated by Django 4.2.4 on 2024-01-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_remove_premieresminiaturesimages_premiere_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingpremieres",
            name="content",
            field=models.CharField(default="something", max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pendingpremieres",
            name="game_title",
            field=models.CharField(default="somethign", max_length=100),
            preserve_default=False,
        ),
    ]
