# Generated by Django 4.2.4 on 2024-01-15 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_pendingpremieres_content_pendingpremieres_game_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsroomminiaturesimages",
            name="news",
        ),
        migrations.AddField(
            model_name="newsroom",
            name="miniatures_image",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.newsroomminiaturesimages",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newsroomminiaturesimages",
            name="description",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newsroomminiaturesimages",
            name="news_title",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
