# Generated by Django 4.2.4 on 2024-01-16 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_remove_newsroomminiaturesimages_news_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rankingsminiaturesimages",
            name="ranking",
        ),
        migrations.AddField(
            model_name="rankings",
            name="ranking_minature_image",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.rankingsminiaturesimages",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rankingsminiaturesimages",
            name="ranking_title",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
